/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.Controller;
import Model.Usuario;
import Model.Veiculo;
import java.awt.Color;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JoseM
 */
public class Definicoes extends javax.swing.JFrame {

    /**
     * Creates new form Definicoes
     */
    public Definicoes() {
        initComponents();
        dtm=(DefaultTableModel)jTable2.getModel();
        this.preencherTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        kPannelMain = new keeptoo.KGradientPanel();
        jPanelButtons = new javax.swing.JPanel();
        btDefUtilizador = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        tfBtDefUtilizador = new javax.swing.JLabel();
        btDefTarifas = new keeptoo.KGradientPanel();
        jLabel3 = new javax.swing.JLabel();
        tfBtDefTarifas = new javax.swing.JLabel();
        btDefAdicionais = new keeptoo.KGradientPanel();
        jLabel5 = new javax.swing.JLabel();
        tfBtDefAdicionais = new javax.swing.JLabel();
        JPanelRoot = new javax.swing.JPanel();
        JPanelUtilizador = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        tfUsername = new javax.swing.JTextField();
        lbPassword = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbCategoria = new javax.swing.JComboBox<>();
        btGravar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        pwPassword = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        btAdicionar = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        JPanelTarifas = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Definições");
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(650, 500));
        setPreferredSize(new java.awt.Dimension(650, 500));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        kPannelMain.setkBorderRadius(0);
        kPannelMain.setkEndColor(new java.awt.Color(0, 204, 255));
        kPannelMain.setkStartColor(new java.awt.Color(255, 255, 255));
        kPannelMain.setMinimumSize(new java.awt.Dimension(670, 500));
        kPannelMain.setPreferredSize(new java.awt.Dimension(670, 500));
        kPannelMain.setLayout(new java.awt.GridBagLayout());

        jPanelButtons.setOpaque(false);
        jPanelButtons.setLayout(new java.awt.GridBagLayout());

        btDefUtilizador.setkBorderRadius(30);
        btDefUtilizador.setkEndColor(new java.awt.Color(153, 255, 255));
        btDefUtilizador.setkStartColor(new java.awt.Color(102, 153, 255));
        btDefUtilizador.setOpaque(false);
        btDefUtilizador.setPreferredSize(new java.awt.Dimension(80, 50));
        btDefUtilizador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btDefUtilizadorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btDefUtilizadorMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btDefUtilizadorMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btDefUtilizadorMouseReleased(evt);
            }
        });
        btDefUtilizador.setLayout(new java.awt.GridBagLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/icons8_User_Account_50px_1.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        btDefUtilizador.add(jLabel1, gridBagConstraints);

        tfBtDefUtilizador.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfBtDefUtilizador.setText("Definições de Utilizador");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 0, 10);
        btDefUtilizador.add(tfBtDefUtilizador, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 0, 4);
        jPanelButtons.add(btDefUtilizador, gridBagConstraints);

        btDefTarifas.setkBorderRadius(30);
        btDefTarifas.setkEndColor(new java.awt.Color(153, 255, 255));
        btDefTarifas.setkStartColor(new java.awt.Color(102, 153, 255));
        btDefTarifas.setkTransparentControls(false);
        btDefTarifas.setOpaque(false);
        btDefTarifas.setPreferredSize(new java.awt.Dimension(80, 50));
        btDefTarifas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btDefTarifasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btDefTarifasMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btDefTarifasMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btDefTarifasMouseReleased(evt);
            }
        });
        btDefTarifas.setLayout(new java.awt.GridBagLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/icons8_Money_Bag_50px.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        btDefTarifas.add(jLabel3, gridBagConstraints);

        tfBtDefTarifas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfBtDefTarifas.setText("Definições de Tarifas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 0, 5);
        btDefTarifas.add(tfBtDefTarifas, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 0, 4);
        jPanelButtons.add(btDefTarifas, gridBagConstraints);

        btDefAdicionais.setkBorderRadius(30);
        btDefAdicionais.setkEndColor(new java.awt.Color(153, 255, 255));
        btDefAdicionais.setkStartColor(new java.awt.Color(102, 153, 255));
        btDefAdicionais.setkTransparentControls(false);
        btDefAdicionais.setOpaque(false);
        btDefAdicionais.setPreferredSize(new java.awt.Dimension(80, 50));
        btDefAdicionais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btDefAdicionaisMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btDefAdicionaisMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btDefAdicionaisMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btDefAdicionaisMouseReleased(evt);
            }
        });
        btDefAdicionais.setLayout(new java.awt.GridBagLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/icons8_Settings_50px_1.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        btDefAdicionais.add(jLabel5, gridBagConstraints);

        tfBtDefAdicionais.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfBtDefAdicionais.setText("Definições de etc....");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 0, 5);
        btDefAdicionais.add(tfBtDefAdicionais, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 0, 4);
        jPanelButtons.add(btDefAdicionais, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.05;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 5, 10);
        kPannelMain.add(jPanelButtons, gridBagConstraints);

        JPanelRoot.setOpaque(false);
        JPanelRoot.setLayout(new java.awt.CardLayout());

        JPanelUtilizador.setOpaque(false);
        JPanelUtilizador.setLayout(new java.awt.GridBagLayout());

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel7.setText(" Nome de Utilizador");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 0);
        jPanel2.add(jLabel7, gridBagConstraints);

        tfUsername.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 20);
        jPanel2.add(tfUsername, gridBagConstraints);

        lbPassword.setText("Palavra-Passe");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 0);
        jPanel2.add(lbPassword, gridBagConstraints);

        jLabel9.setText("Categoria");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 0);
        jPanel2.add(jLabel9, gridBagConstraints);

        cbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gestor", "Utilizador" }));
        cbCategoria.setEnabled(false);
        cbCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCategoriaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 20);
        jPanel2.add(cbCategoria, gridBagConstraints);

        btGravar.setText("Guardar");
        btGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGravarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        jPanel2.add(btGravar, gridBagConstraints);

        jLabel10.setForeground(new java.awt.Color(0, 153, 51));
        jLabel10.setText("Registrado com sucesso");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 0);
        jPanel2.add(jLabel10, gridBagConstraints);

        pwPassword.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 20);
        jPanel2.add(pwPassword, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        JPanelUtilizador.add(jPanel2, gridBagConstraints);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridBagLayout());

        btAdicionar.setText("Adicionar");
        btAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(btAdicionar, gridBagConstraints);

        btAlterar.setText("Alterar");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(btAlterar, gridBagConstraints);

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(btCancelar, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        JPanelUtilizador.add(jPanel1, gridBagConstraints);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome de Utilizador", "Tipo", "Ultimo Login"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        JPanelUtilizador.add(jScrollPane2, gridBagConstraints);

        JPanelRoot.add(JPanelUtilizador, "card2");

        JPanelTarifas.setOpaque(false);
        JPanelTarifas.setLayout(new java.awt.GridBagLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Custos de veículos"));
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jLabel2.setText("Aberto(por KG)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel3.add(jLabel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel3.add(jTextField1, gridBagConstraints);

        jLabel4.setText("Fechado (Por KG)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel3.add(jLabel4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel3.add(jTextField2, gridBagConstraints);

        jLabel6.setText("Basculante(por KG)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel3.add(jLabel6, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel3.add(jTextField3, gridBagConstraints);

        jLabel8.setText("P/ Contentor(por KG)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel3.add(jLabel8, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel3.add(jTextField4, gridBagConstraints);

        jLabel11.setText("Frigorífico(por litro)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel3.add(jLabel11, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel3.add(jTextField5, gridBagConstraints);

        jLabel12.setText("Tanque(por litro)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel3.add(jLabel12, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel3.add(jTextField6, gridBagConstraints);

        jLabel19.setText("Bus(por lugar)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel3.add(jLabel19, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel3.add(jTextField13, gridBagConstraints);

        jLabel20.setText("Automóvel(p/ lugar)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel3.add(jLabel20, gridBagConstraints);

        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel3.add(jTextField14, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        JPanelTarifas.add(jPanel3, gridBagConstraints);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Custos de recursos"));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel13.setText("Alojamento (por 500KM)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel4.add(jLabel13, gridBagConstraints);

        jLabel14.setText("jLabel14");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel4.add(jLabel14, gridBagConstraints);

        jLabel15.setText("jLabel15");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel4.add(jLabel15, gridBagConstraints);

        jLabel16.setText("jLabel16");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel4.add(jLabel16, gridBagConstraints);

        jLabel17.setText("jLabel17");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel4.add(jLabel17, gridBagConstraints);

        jLabel18.setText("jLabel18");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel4.add(jLabel18, gridBagConstraints);

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel4.add(jTextField7, gridBagConstraints);

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel4.add(jTextField8, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel4.add(jTextField9, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel4.add(jTextField10, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel4.add(jTextField11, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel4.add(jTextField12, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        JPanelTarifas.add(jPanel4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 0.08;
        JPanelTarifas.add(jPanel5, gridBagConstraints);

        JPanelRoot.add(JPanelTarifas, "card2");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        kPannelMain.add(JPanelRoot, gridBagConstraints);

        getContentPane().add(kPannelMain);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btDefUtilizadorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDefUtilizadorMouseEntered
        // TODO add your handling code here:
        btDefUtilizador.setkStartColor(new Color(122,173,255));
        btDefUtilizador.setkEndColor(new Color(183,255,255));
        
        
        //new Color(122,173,255)
        this.revalidate();
        this.repaint();
        
    }//GEN-LAST:event_btDefUtilizadorMouseEntered

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        tfUsername.setText("");
        pwPassword.setText("");
        
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btDefUtilizadorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDefUtilizadorMouseExited
        // TODO add your handling code here:
         btDefUtilizador.setkStartColor(new Color(102,153,255));
        btDefUtilizador.setkEndColor(new Color(153,255,255));
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_btDefUtilizadorMouseExited

    private void btDefUtilizadorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDefUtilizadorMousePressed
        // TODO add your handling code here:
        tfBtDefUtilizador.setFont(new java.awt.Font("Tahoma", 1, 13));
        
        
        JPanelRoot.removeAll();
        JPanelRoot.add(JPanelUtilizador);
        JPanelRoot.repaint();
        JPanelRoot.revalidate(); 
        
        
    }//GEN-LAST:event_btDefUtilizadorMousePressed

    private void btDefUtilizadorMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDefUtilizadorMouseReleased
        // TODO add your handling code here:
         tfBtDefUtilizador.setFont(new java.awt.Font("Tahoma", 0, 14));
    }//GEN-LAST:event_btDefUtilizadorMouseReleased

    private void btDefTarifasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDefTarifasMouseEntered
        // TODO add your handling code here:
        btDefTarifas.setkStartColor(new Color(122,173,255));
        btDefTarifas.setkEndColor(new Color(183,255,255));
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_btDefTarifasMouseEntered

    private void btDefTarifasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDefTarifasMouseExited
        // TODO add your handling code here:
         btDefTarifas.setkStartColor(new Color(102,153,255));
         btDefTarifas.setkEndColor(new Color(153,255,255));
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_btDefTarifasMouseExited

    private void btDefTarifasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDefTarifasMousePressed
        // TODO add your handling code here:
        tfBtDefTarifas.setFont(new java.awt.Font("Tahoma", 1, 13));
        
        JPanelRoot.removeAll();
        JPanelRoot.add(JPanelTarifas);
        JPanelRoot.repaint();
        JPanelRoot.revalidate();
        
    }//GEN-LAST:event_btDefTarifasMousePressed

    private void btDefTarifasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDefTarifasMouseReleased
        // TODO add your handling code here:
        tfBtDefTarifas.setFont(new java.awt.Font("Tahoma", 0, 14));
    }//GEN-LAST:event_btDefTarifasMouseReleased

    private void btDefAdicionaisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDefAdicionaisMouseEntered
        // TODO add your handling code here:
         btDefAdicionais.setkStartColor(new Color(122,173,255));
         btDefAdicionais.setkEndColor(new Color(183,255,255));
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_btDefAdicionaisMouseEntered

    private void btDefAdicionaisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDefAdicionaisMouseExited
        // TODO add your handling code here:
        btDefAdicionais.setkStartColor(new Color(102,153,255));
        btDefAdicionais.setkEndColor(new Color(153,255,255));
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_btDefAdicionaisMouseExited

    private void btDefAdicionaisMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDefAdicionaisMousePressed
        // TODO add your handling code here:
        tfBtDefAdicionais.setFont(new java.awt.Font("Tahoma", 1, 13));
    }//GEN-LAST:event_btDefAdicionaisMousePressed

    private void btDefAdicionaisMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDefAdicionaisMouseReleased
        // TODO add your handling code here:
        tfBtDefAdicionais.setFont(new java.awt.Font("Tahoma", 0, 14));
    }//GEN-LAST:event_btDefAdicionaisMouseReleased

    private void btAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarActionPerformed
        // TODO add your handling code here:
        tfUsername.setEnabled(true);
        pwPassword.setEnabled(true);
        cbCategoria.setEnabled(true);
        tfUsername.setText("");
        pwPassword.setText("");
        
    }//GEN-LAST:event_btAdicionarActionPerformed

    private void btGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGravarActionPerformed
        
        String tipo=(String)cbCategoria.getSelectedItem();
        Usuario usr=new Usuario(tfUsername.getText(), new String(pwPassword.getPassword()),tipo);
        
        if(btGravar.getText().equalsIgnoreCase("guardar")){
            System.out.println(usr.gravar());
            JOptionPane.showMessageDialog(this, "Usuario Registado");
            this.limparTabela();
            this.preencherTabela();
        }
        else if(btGravar.getText().equalsIgnoreCase("alterar")){
            
            usr.setId(a.getId());
            System.out.println(usr.gravar());
            JOptionPane.showMessageDialog(this,"Dados Alterados");
            this.limparTabela();
            this.preencherTabela();
        }
        
    }//GEN-LAST:event_btGravarActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        
        tfUsername.setEnabled(true);
        pwPassword.setEnabled(true);
        cbCategoria.setEnabled(true);
        lbPassword.setText("Nova Senha");
        btGravar.setText("Alterar");
        
        String nome=(String)jTable2.getValueAt(jTable2.getSelectedRow(), 0);
        
        for(Usuario u:todosUsers){
        
            if(u.getNome().equalsIgnoreCase(nome)){
                System.out.println("Nome igual");
                tfUsername.setText(nome);
                pwPassword.setText(new String(u.getSenha()));
                pwPassword.setFocusable(true);
                cbCategoria.setSelectedItem(u.getTipo());
                a=u;
                
            }
        }

    }//GEN-LAST:event_btAlterarActionPerformed

    private void cbCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCategoriaActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Definicoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Definicoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Definicoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Definicoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Definicoes().setVisible(true);
            }
        });
    }
    
    public void preencherTabela(){
        this.limparTabela();
        controller=new Controller<Usuario>(Usuario.class);
        todosUsers=(List<Usuario>)controller.getDados();

        //DefaultTableModel dtm=(DefaultTableModel)jTable2.getModel(); 
        
        for(Usuario usr:todosUsers){
            
            Date ul=usr.getDataUltimoLog();
            String data=null;
            
            if(ul!=null){
            
                DateFormat df=DateFormat.getDateTimeInstance(DateFormat.SHORT, DateFormat.SHORT);
                data=df.format(ul);
            }
            
            String dados[]={usr.getNome(),usr.getTipo(),data};
            
            dtm.addRow(dados);
        }
    }
    
    public void limparTabela(){
        
        DefaultTableModel dtm=(DefaultTableModel)jTable2.getModel();
        
        System.out.println(dtm.getRowCount());
        int linhas=dtm.getRowCount();
        
        for(int i=linhas-1;i>=0;i--){
          dtm.removeRow(i);  
        }
            
        
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelRoot;
    private javax.swing.JPanel JPanelTarifas;
    private javax.swing.JPanel JPanelUtilizador;
    private javax.swing.JButton btAdicionar;
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btCancelar;
    private keeptoo.KGradientPanel btDefAdicionais;
    private keeptoo.KGradientPanel btDefTarifas;
    private keeptoo.KGradientPanel btDefUtilizador;
    private javax.swing.JButton btGravar;
    private javax.swing.JComboBox<String> cbCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelButtons;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private keeptoo.KGradientPanel kPannelMain;
    private javax.swing.JLabel lbPassword;
    private javax.swing.JPasswordField pwPassword;
    private javax.swing.JLabel tfBtDefAdicionais;
    private javax.swing.JLabel tfBtDefTarifas;
    private javax.swing.JLabel tfBtDefUtilizador;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
    Controller<Usuario> controller;
    List<Usuario> todosUsers;
    DefaultTableModel dtm;
    Usuario a;
}
