/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import keeptoo.Drag;

/**
 *
 * @author JoseM
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home(String username) {
        
        initComponents();
        lbUserNameHome.setText(username);
        lbNotificacoes.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jProgressBarLU1 = new com.alee.managers.language.updaters.JProgressBarLU();
        webProgressBarUI1 = new com.alee.laf.progressbar.WebProgressBarUI();
        webStepProgressStyle1 = new com.alee.extended.progress.WebStepProgressStyle();
        webProgressBarStyle1 = new com.alee.laf.progressbar.WebProgressBarStyle();
        webStepProgress1 = new com.alee.extended.progress.WebStepProgress();
        jPanelMenu = new javax.swing.JPanel();
        kbtRViagem = new keeptoo.KButton();
        kbtRelatorios = new keeptoo.KButton();
        kbtVViagens = new keeptoo.KButton();
        kbtGViaturas = new keeptoo.KButton();
        kbtGFuncionarios = new keeptoo.KButton();
        btSettings = new javax.swing.JLabel();
        kPanelRoot = new keeptoo.KGradientPanel();
        kPanelHome = new keeptoo.KGradientPanel();
        kPanelPendentes = new keeptoo.KGradientPanel();
        lbPendentesTop = new javax.swing.JLabel();
        lbPendentes = new javax.swing.JLabel();
        kPanelEmCurso = new keeptoo.KGradientPanel();
        lbEmCursoTop = new javax.swing.JLabel();
        lbEmCurso = new javax.swing.JLabel();
        kPanelTerminadas = new keeptoo.KGradientPanel();
        lbTerminadasTop = new javax.swing.JLabel();
        lbTerminadas = new javax.swing.JLabel();
        lbUltimasViagens = new javax.swing.JLabel();
        progressHome1 = new com.alee.laf.progressbar.WebProgressBar();
        lbClienteHome = new javax.swing.JLabel();
        lbOrigemHome = new javax.swing.JLabel();
        lbDestinoHome = new javax.swing.JLabel();
        lbClienteHome1 = new javax.swing.JLabel();
        sepHome = new javax.swing.JSeparator();
        lbOrigemHome1 = new javax.swing.JLabel();
        lbDestinohome1 = new javax.swing.JLabel();
        lbClienteHome2 = new javax.swing.JLabel();
        webProgressBar2 = new com.alee.laf.progressbar.WebProgressBar();
        lbOrigemHome2 = new javax.swing.JLabel();
        lbDestinoHome2 = new javax.swing.JLabel();
        lbClienteHome3 = new javax.swing.JLabel();
        progressHome3 = new com.alee.laf.progressbar.WebProgressBar();
        lbOrigemHome3 = new javax.swing.JLabel();
        lbDestinoHome3 = new javax.swing.JLabel();
        lbOrigemHome4 = new javax.swing.JLabel();
        lbClienteHome4 = new javax.swing.JLabel();
        lbDestinoHome4 = new javax.swing.JLabel();
        webProgressBar5 = new com.alee.laf.progressbar.WebProgressBar();
        kPanelRViagem = new keeptoo.KGradientPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        kPanelVViagens = new keeptoo.KGradientPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        kPanelGViaturas = new keeptoo.KGradientPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        btEditarViaturas = new keeptoo.KButton();
        kButton2 = new keeptoo.KButton();
        btVerViaturas = new keeptoo.KButton();
        kPanelGViaturas1 = new keeptoo.KGradientPanel();
        kPanelGFRoot = new keeptoo.KGradientPanel();
        kPanelGFuncionarios = new keeptoo.KGradientPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        btPaneVerFunc = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btPaneAddFunc = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btPaneAlterFunc = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        kPanelVerFunc = new keeptoo.KGradientPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        rSPanelShadow1 = new rojeru_san.RSPanelShadow();
        jLabel1 = new javax.swing.JLabel();
        rSPanelShadow2 = new rojeru_san.RSPanelShadow();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        rSPanelShadow3 = new rojeru_san.RSPanelShadow();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        rSPanelShadow4 = new rojeru_san.RSPanelShadow();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        kPanelRelatorios = new keeptoo.KGradientPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        kPanelNorth = new keeptoo.KGradientPanel();
        lbUserNameHome = new javax.swing.JLabel();
        btNotificacoes = new javax.swing.JLabel();
        lbNotificacoes = new javax.swing.JLabel();
        kPanelTitleBar = new keeptoo.KGradientPanel();
        btExit = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelMenu.setBackground(new java.awt.Color(255, 255, 255));

        kbtRViagem.setBackground(new java.awt.Color(236, 236, 236));
        kbtRViagem.setForeground(new java.awt.Color(0, 0, 0));
        kbtRViagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/icons8_Truck_30px.png"))); // NOI18N
        kbtRViagem.setText("  Registrar Viagem");
        kbtRViagem.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        kbtRViagem.setkAllowGradient(false);
        kbtRViagem.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        kbtRViagem.setkBorderRadius(0);
        kbtRViagem.setkEndColor(new java.awt.Color(0, 255, 255));
        kbtRViagem.setkForeGround(new java.awt.Color(0, 0, 0));
        kbtRViagem.setkHoverForeGround(new java.awt.Color(102, 102, 102));
        kbtRViagem.setkPressedColor(new java.awt.Color(255, 255, 255));
        kbtRViagem.setkSelectedColor(new java.awt.Color(101, 198, 187));
        kbtRViagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kbtRViagemActionPerformed(evt);
            }
        });

        kbtRelatorios.setBackground(new java.awt.Color(236, 236, 236));
        kbtRelatorios.setForeground(new java.awt.Color(0, 0, 0));
        kbtRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/icons8_Stop_Pie_Chart_Report_30px.png"))); // NOI18N
        kbtRelatorios.setText("Relatórios");
        kbtRelatorios.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        kbtRelatorios.setkAllowGradient(false);
        kbtRelatorios.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        kbtRelatorios.setkBorderRadius(0);
        kbtRelatorios.setkEndColor(new java.awt.Color(0, 255, 255));
        kbtRelatorios.setkForeGround(new java.awt.Color(0, 0, 0));
        kbtRelatorios.setkHoverForeGround(new java.awt.Color(102, 102, 102));
        kbtRelatorios.setkPressedColor(new java.awt.Color(255, 255, 255));
        kbtRelatorios.setkSelectedColor(new java.awt.Color(101, 198, 187));
        kbtRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kbtRelatoriosActionPerformed(evt);
            }
        });

        kbtVViagens.setBackground(new java.awt.Color(236, 236, 236));
        kbtVViagens.setForeground(new java.awt.Color(0, 0, 0));
        kbtVViagens.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/icons8_Traveler_30px_3.png"))); // NOI18N
        kbtVViagens.setText("Ver viagens");
        kbtVViagens.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        kbtVViagens.setkAllowGradient(false);
        kbtVViagens.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        kbtVViagens.setkBorderRadius(0);
        kbtVViagens.setkEndColor(new java.awt.Color(0, 255, 255));
        kbtVViagens.setkForeGround(new java.awt.Color(0, 0, 0));
        kbtVViagens.setkHoverForeGround(new java.awt.Color(102, 102, 102));
        kbtVViagens.setkPressedColor(new java.awt.Color(255, 255, 255));
        kbtVViagens.setkSelectedColor(new java.awt.Color(101, 198, 187));
        kbtVViagens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kbtVViagensActionPerformed(evt);
            }
        });

        kbtGViaturas.setBackground(new java.awt.Color(236, 236, 236));
        kbtGViaturas.setForeground(new java.awt.Color(0, 0, 0));
        kbtGViaturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/icons8_Car_Service_30px_1.png"))); // NOI18N
        kbtGViaturas.setText("Gerir Viaturas");
        kbtGViaturas.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        kbtGViaturas.setkAllowGradient(false);
        kbtGViaturas.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        kbtGViaturas.setkBorderRadius(0);
        kbtGViaturas.setkEndColor(new java.awt.Color(0, 255, 255));
        kbtGViaturas.setkForeGround(new java.awt.Color(0, 0, 0));
        kbtGViaturas.setkHoverForeGround(new java.awt.Color(102, 102, 102));
        kbtGViaturas.setkPressedColor(new java.awt.Color(255, 255, 255));
        kbtGViaturas.setkSelectedColor(new java.awt.Color(101, 198, 187));
        kbtGViaturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kbtGViaturasActionPerformed(evt);
            }
        });

        kbtGFuncionarios.setBackground(new java.awt.Color(236, 236, 236));
        kbtGFuncionarios.setForeground(new java.awt.Color(0, 0, 0));
        kbtGFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/icons8_People_30px.png"))); // NOI18N
        kbtGFuncionarios.setText("Gerir Funcionários");
        kbtGFuncionarios.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        kbtGFuncionarios.setkAllowGradient(false);
        kbtGFuncionarios.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        kbtGFuncionarios.setkBorderRadius(0);
        kbtGFuncionarios.setkEndColor(new java.awt.Color(0, 255, 255));
        kbtGFuncionarios.setkForeGround(new java.awt.Color(0, 0, 0));
        kbtGFuncionarios.setkHoverForeGround(new java.awt.Color(102, 102, 102));
        kbtGFuncionarios.setkPressedColor(new java.awt.Color(255, 255, 255));
        kbtGFuncionarios.setkSelectedColor(new java.awt.Color(101, 198, 187));
        kbtGFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kbtGFuncionariosActionPerformed(evt);
            }
        });

        btSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/icons8_Services_30px.png"))); // NOI18N

        javax.swing.GroupLayout jPanelMenuLayout = new javax.swing.GroupLayout(jPanelMenu);
        jPanelMenu.setLayout(jPanelMenuLayout);
        jPanelMenuLayout.setHorizontalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMenuLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(kbtRelatorios, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(kbtGFuncionarios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(kbtGViaturas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(kbtRViagem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(kbtVViagens, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(jPanelMenuLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(btSettings)))
                .addGap(5, 5, 5))
        );
        jPanelMenuLayout.setVerticalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addComponent(kbtRViagem, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kbtVViagens, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(kbtGViaturas, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(kbtGFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(kbtRelatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 180, 470));

        kPanelRoot.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 0, new java.awt.Color(204, 204, 204)));
        kPanelRoot.setForeground(new java.awt.Color(204, 204, 204));
        kPanelRoot.setkBorderRadius(0);
        kPanelRoot.setkEndColor(new java.awt.Color(204, 255, 255));
        kPanelRoot.setkStartColor(new java.awt.Color(255, 255, 255));
        kPanelRoot.setLayout(new java.awt.CardLayout());

        kPanelHome.setkBorderRadius(0);
        kPanelHome.setkEndColor(new java.awt.Color(204, 255, 255));
        kPanelHome.setkStartColor(new java.awt.Color(255, 255, 255));

        kPanelPendentes.setkEndColor(new java.awt.Color(242, 38, 19));
        kPanelPendentes.setkStartColor(new java.awt.Color(242, 23, 153));

        lbPendentesTop.setText("Viagens Pendentes");

        lbPendentes.setFont(new java.awt.Font("Josefin Sans", 1, 36)); // NOI18N
        lbPendentes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPendentes.setText("0");

        javax.swing.GroupLayout kPanelPendentesLayout = new javax.swing.GroupLayout(kPanelPendentes);
        kPanelPendentes.setLayout(kPanelPendentesLayout);
        kPanelPendentesLayout.setHorizontalGroup(
            kPanelPendentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kPanelPendentesLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(kPanelPendentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbPendentesTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbPendentes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(45, 45, 45))
        );
        kPanelPendentesLayout.setVerticalGroup(
            kPanelPendentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kPanelPendentesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbPendentesTop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbPendentes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        kPanelEmCurso.setkEndColor(new java.awt.Color(52, 152, 219));
        kPanelEmCurso.setkStartColor(new java.awt.Color(129, 207, 224));

        lbEmCursoTop.setText("Viagens em curso");

        lbEmCurso.setFont(new java.awt.Font("Josefin Sans", 1, 36)); // NOI18N
        lbEmCurso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbEmCurso.setText("0");

        javax.swing.GroupLayout kPanelEmCursoLayout = new javax.swing.GroupLayout(kPanelEmCurso);
        kPanelEmCurso.setLayout(kPanelEmCursoLayout);
        kPanelEmCursoLayout.setHorizontalGroup(
            kPanelEmCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kPanelEmCursoLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(kPanelEmCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbEmCursoTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbEmCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        kPanelEmCursoLayout.setVerticalGroup(
            kPanelEmCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kPanelEmCursoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbEmCursoTop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbEmCurso, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        kPanelTerminadas.setkEndColor(new java.awt.Color(0, 0, 0));
        kPanelTerminadas.setkStartColor(new java.awt.Color(0, 230, 64));

        lbTerminadasTop.setText("Viagens terminadas");

        lbTerminadas.setFont(new java.awt.Font("Josefin Sans", 1, 36)); // NOI18N
        lbTerminadas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTerminadas.setText("0");

        javax.swing.GroupLayout kPanelTerminadasLayout = new javax.swing.GroupLayout(kPanelTerminadas);
        kPanelTerminadas.setLayout(kPanelTerminadasLayout);
        kPanelTerminadasLayout.setHorizontalGroup(
            kPanelTerminadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kPanelTerminadasLayout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(kPanelTerminadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbTerminadasTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbTerminadas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(45, 45, 45))
        );
        kPanelTerminadasLayout.setVerticalGroup(
            kPanelTerminadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kPanelTerminadasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTerminadasTop, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTerminadas, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        lbUltimasViagens.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbUltimasViagens.setText("Últimas Viagens");

        progressHome1.setValue(80);
        progressHome1.setBgBottom(new java.awt.Color(204, 255, 255));
        progressHome1.setBgTop(new java.awt.Color(204, 204, 255));
        progressHome1.setProgressBottomColor(new java.awt.Color(51, 255, 255));
        progressHome1.setProgressTopColor(new java.awt.Color(51, 255, 0));

        lbClienteHome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbClienteHome.setText("Cliente");

        lbOrigemHome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbOrigemHome.setText("Origem");

        lbDestinoHome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbDestinoHome.setText("Destino");

        lbClienteHome1.setText("Pepsi co.");

        lbOrigemHome1.setText("Maputo - Cidade");

        lbDestinohome1.setText("Zambezia - Quelimane");

        lbClienteHome2.setText("Mozal");

        webProgressBar2.setValue(20);
        webProgressBar2.setBgBottom(new java.awt.Color(204, 255, 255));
        webProgressBar2.setBgTop(new java.awt.Color(204, 204, 255));
        webProgressBar2.setProgressBottomColor(new java.awt.Color(51, 255, 255));
        webProgressBar2.setProgressTopColor(new java.awt.Color(51, 255, 0));

        lbOrigemHome2.setText("Maputo - Província");

        lbDestinoHome2.setText("SA - Johanesburg");

        lbClienteHome3.setText("Fematro");

        progressHome3.setValue(56);
        progressHome3.setBgBottom(new java.awt.Color(204, 255, 255));
        progressHome3.setBgTop(new java.awt.Color(204, 204, 255));
        progressHome3.setProgressBottomColor(new java.awt.Color(51, 255, 255));
        progressHome3.setProgressTopColor(new java.awt.Color(51, 255, 0));

        lbOrigemHome3.setText("Maputo - Junta");

        lbDestinoHome3.setText("Inhambane - Maxixe");

        lbOrigemHome4.setText("Nampula - Nacala");

        lbClienteHome4.setText("Maningue Nice");

        lbDestinoHome4.setText("Sofala - Beira");

        webProgressBar5.setValue(90);
        webProgressBar5.setBgBottom(new java.awt.Color(204, 255, 255));
        webProgressBar5.setBgTop(new java.awt.Color(204, 204, 255));
        webProgressBar5.setProgressBottomColor(new java.awt.Color(51, 255, 255));
        webProgressBar5.setProgressTopColor(new java.awt.Color(51, 255, 0));

        javax.swing.GroupLayout kPanelHomeLayout = new javax.swing.GroupLayout(kPanelHome);
        kPanelHome.setLayout(kPanelHomeLayout);
        kPanelHomeLayout.setHorizontalGroup(
            kPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kPanelHomeLayout.createSequentialGroup()
                .addGroup(kPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kPanelHomeLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(kPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kPanelHomeLayout.createSequentialGroup()
                                .addComponent(kPanelPendentes, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(kPanelEmCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(kPanelTerminadas, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbUltimasViagens, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(kPanelHomeLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(kPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(kPanelHomeLayout.createSequentialGroup()
                                .addComponent(lbClienteHome1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbOrigemHome1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbDestinohome1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(kPanelHomeLayout.createSequentialGroup()
                                .addComponent(lbClienteHome, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(lbOrigemHome, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbDestinoHome, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(progressHome1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sepHome, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(kPanelHomeLayout.createSequentialGroup()
                                .addComponent(lbClienteHome2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbOrigemHome2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbDestinoHome2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(webProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(kPanelHomeLayout.createSequentialGroup()
                                .addComponent(lbClienteHome3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbOrigemHome3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbDestinoHome3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(progressHome3, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(kPanelHomeLayout.createSequentialGroup()
                                .addComponent(lbClienteHome4, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbOrigemHome4, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbDestinoHome4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(webProgressBar5, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kPanelHomeLayout.setVerticalGroup(
            kPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kPanelHomeLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(kPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kPanelTerminadas, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kPanelEmCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kPanelPendentes, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(lbUltimasViagens, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(kPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbClienteHome)
                    .addComponent(lbOrigemHome)
                    .addComponent(lbDestinoHome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sepHome, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbClienteHome1)
                    .addComponent(lbOrigemHome1)
                    .addComponent(lbDestinohome1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressHome1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(kPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbClienteHome2)
                    .addComponent(lbOrigemHome2)
                    .addComponent(lbDestinoHome2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(webProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(kPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbClienteHome3)
                    .addComponent(lbOrigemHome3)
                    .addComponent(lbDestinoHome3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressHome3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(kPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbClienteHome4)
                    .addGroup(kPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbDestinoHome4)
                        .addComponent(lbOrigemHome4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(webProgressBar5, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        kPanelRoot.add(kPanelHome, "card2");

        kPanelRViagem.setkBorderRadius(0);
        kPanelRViagem.setkEndColor(new java.awt.Color(204, 255, 255));
        kPanelRViagem.setkStartColor(new java.awt.Color(255, 255, 255));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/icons8_Back_Arrow_30px_2.png"))); // NOI18N
        jLabel26.setText("Voltar");
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel26MouseClicked(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel27.setText("Registrar viagem");

        javax.swing.GroupLayout kPanelRViagemLayout = new javax.swing.GroupLayout(kPanelRViagem);
        kPanelRViagem.setLayout(kPanelRViagemLayout);
        kPanelRViagemLayout.setHorizontalGroup(
            kPanelRViagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kPanelRViagemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addGap(176, 176, 176)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kPanelRViagemLayout.setVerticalGroup(
            kPanelRViagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kPanelRViagemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kPanelRViagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27))
                .addContainerGap(429, Short.MAX_VALUE))
        );

        kPanelRoot.add(kPanelRViagem, "card2");

        kPanelVViagens.setkBorderRadius(0);
        kPanelVViagens.setkEndColor(new java.awt.Color(204, 255, 255));
        kPanelVViagens.setkStartColor(new java.awt.Color(255, 255, 255));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/icons8_Back_Arrow_30px_2.png"))); // NOI18N
        jLabel28.setText("Voltar");
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel28MouseClicked(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel29.setText("Ver Viagens");

        javax.swing.GroupLayout kPanelVViagensLayout = new javax.swing.GroupLayout(kPanelVViagens);
        kPanelVViagens.setLayout(kPanelVViagensLayout);
        kPanelVViagensLayout.setHorizontalGroup(
            kPanelVViagensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kPanelVViagensLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28)
                .addGap(176, 176, 176)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kPanelVViagensLayout.setVerticalGroup(
            kPanelVViagensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kPanelVViagensLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kPanelVViagensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29))
                .addContainerGap(429, Short.MAX_VALUE))
        );

        kPanelRoot.add(kPanelVViagens, "card2");

        kPanelGViaturas.setkBorderRadius(0);
        kPanelGViaturas.setkEndColor(new java.awt.Color(204, 255, 255));
        kPanelGViaturas.setkStartColor(new java.awt.Color(255, 255, 255));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/icons8_Back_Arrow_30px_2.png"))); // NOI18N
        jLabel30.setText("Voltar");
        jLabel30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel30MouseClicked(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel31.setText("Gerir viaturas");

        btEditarViaturas.setText("Alterar Viaturas");
        btEditarViaturas.setkBackGroundColor(new java.awt.Color(0, 0, 0));
        btEditarViaturas.setkEndColor(new java.awt.Color(255, 255, 255));
        btEditarViaturas.setkHoverEndColor(new java.awt.Color(204, 204, 204));
        btEditarViaturas.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btEditarViaturas.setkHoverStartColor(new java.awt.Color(0, 153, 153));
        btEditarViaturas.setkSelectedColor(new java.awt.Color(0, 204, 204));

        kButton2.setText("Adicionar Viaturas");
        kButton2.setkBackGroundColor(new java.awt.Color(0, 0, 0));
        kButton2.setkEndColor(new java.awt.Color(255, 255, 255));
        kButton2.setkHoverEndColor(new java.awt.Color(204, 204, 204));
        kButton2.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton2.setkHoverStartColor(new java.awt.Color(0, 153, 153));
        kButton2.setkSelectedColor(new java.awt.Color(0, 204, 204));

        btVerViaturas.setText("Ver Viaturas");
        btVerViaturas.setkBackGroundColor(new java.awt.Color(0, 0, 0));
        btVerViaturas.setkEndColor(new java.awt.Color(255, 255, 255));
        btVerViaturas.setkHoverEndColor(new java.awt.Color(204, 204, 204));
        btVerViaturas.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btVerViaturas.setkHoverStartColor(new java.awt.Color(0, 153, 153));
        btVerViaturas.setkSelectedColor(new java.awt.Color(0, 204, 204));

        kPanelGViaturas1.setkBorderRadius(0);
        kPanelGViaturas1.setkEndColor(new java.awt.Color(204, 255, 255));
        kPanelGViaturas1.setkStartColor(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout kPanelGViaturas1Layout = new javax.swing.GroupLayout(kPanelGViaturas1);
        kPanelGViaturas1.setLayout(kPanelGViaturas1Layout);
        kPanelGViaturas1Layout.setHorizontalGroup(
            kPanelGViaturas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        kPanelGViaturas1Layout.setVerticalGroup(
            kPanelGViaturas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout kPanelGViaturasLayout = new javax.swing.GroupLayout(kPanelGViaturas);
        kPanelGViaturas.setLayout(kPanelGViaturasLayout);
        kPanelGViaturasLayout.setHorizontalGroup(
            kPanelGViaturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kPanelGViaturasLayout.createSequentialGroup()
                .addGroup(kPanelGViaturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kPanelGViaturasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel30)
                        .addGap(176, 176, 176)
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kPanelGViaturasLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btVerViaturas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btEditarViaturas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
            .addComponent(kPanelGViaturas1, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
        );
        kPanelGViaturasLayout.setVerticalGroup(
            kPanelGViaturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kPanelGViaturasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kPanelGViaturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kPanelGViaturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btVerViaturas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btEditarViaturas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(kPanelGViaturas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        kPanelRoot.add(kPanelGViaturas, "card2");

        kPanelGFRoot.setkBorderRadius(0);
        kPanelGFRoot.setkEndColor(new java.awt.Color(204, 255, 255));
        kPanelGFRoot.setkStartColor(new java.awt.Color(255, 255, 255));
        kPanelGFRoot.setLayout(new java.awt.CardLayout());

        kPanelGFuncionarios.setkBorderRadius(0);
        kPanelGFuncionarios.setkEndColor(new java.awt.Color(204, 255, 255));
        kPanelGFuncionarios.setkStartColor(new java.awt.Color(255, 255, 255));

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/icons8_Back_Arrow_30px_2.png"))); // NOI18N
        jLabel36.setText("Voltar");
        jLabel36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel36MouseClicked(evt);
            }
        });

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel37.setText("Gerir Funcionários");

        btPaneVerFunc.setBackground(new java.awt.Color(102, 255, 255));
        btPaneVerFunc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btPaneVerFuncMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btPaneVerFuncMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btPaneVerFuncMousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Ver Funcionários");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/icons8_Contact_50px.png"))); // NOI18N

        javax.swing.GroupLayout btPaneVerFuncLayout = new javax.swing.GroupLayout(btPaneVerFunc);
        btPaneVerFunc.setLayout(btPaneVerFuncLayout);
        btPaneVerFuncLayout.setHorizontalGroup(
            btPaneVerFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btPaneVerFuncLayout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(60, 60, 60))
        );
        btPaneVerFuncLayout.setVerticalGroup(
            btPaneVerFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btPaneVerFuncLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        btPaneAddFunc.setBackground(new java.awt.Color(102, 255, 255));
        btPaneAddFunc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btPaneAddFuncMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btPaneAddFuncMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btPaneAddFuncMousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Adicionar Funcionário");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/icons8_Add_User_Male_50px.png"))); // NOI18N

        javax.swing.GroupLayout btPaneAddFuncLayout = new javax.swing.GroupLayout(btPaneAddFunc);
        btPaneAddFunc.setLayout(btPaneAddFuncLayout);
        btPaneAddFuncLayout.setHorizontalGroup(
            btPaneAddFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btPaneAddFuncLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(60, 60, 60))
        );
        btPaneAddFuncLayout.setVerticalGroup(
            btPaneAddFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btPaneAddFuncLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        btPaneAlterFunc.setBackground(new java.awt.Color(102, 255, 255));
        btPaneAlterFunc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btPaneAlterFuncMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btPaneAlterFuncMouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Alterar");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/icons8_ID_Card_50px.png"))); // NOI18N

        javax.swing.GroupLayout btPaneAlterFuncLayout = new javax.swing.GroupLayout(btPaneAlterFunc);
        btPaneAlterFunc.setLayout(btPaneAlterFuncLayout);
        btPaneAlterFuncLayout.setHorizontalGroup(
            btPaneAlterFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(btPaneAlterFuncLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel8)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        btPaneAlterFuncLayout.setVerticalGroup(
            btPaneAlterFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btPaneAlterFuncLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout kPanelGFuncionariosLayout = new javax.swing.GroupLayout(kPanelGFuncionarios);
        kPanelGFuncionarios.setLayout(kPanelGFuncionariosLayout);
        kPanelGFuncionariosLayout.setHorizontalGroup(
            kPanelGFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kPanelGFuncionariosLayout.createSequentialGroup()
                .addGroup(kPanelGFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kPanelGFuncionariosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel36)
                        .addGap(176, 176, 176)
                        .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kPanelGFuncionariosLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btPaneVerFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btPaneAddFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btPaneAlterFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kPanelGFuncionariosLayout.setVerticalGroup(
            kPanelGFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kPanelGFuncionariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kPanelGFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btPaneAlterFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(kPanelGFuncionariosLayout.createSequentialGroup()
                        .addGroup(kPanelGFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel36)
                            .addComponent(jLabel37))
                        .addGap(134, 134, 134)
                        .addGroup(kPanelGFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btPaneVerFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btPaneAddFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        kPanelGFRoot.add(kPanelGFuncionarios, "card2");

        kPanelVerFunc.setkBorderRadius(0);
        kPanelVerFunc.setkEndColor(new java.awt.Color(204, 255, 255));
        kPanelVerFunc.setkStartColor(new java.awt.Color(255, 255, 255));
        kPanelVerFunc.setMaximumSize(new java.awt.Dimension(380, 280));

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/icons8_Back_Arrow_30px_2.png"))); // NOI18N
        jLabel38.setText("Voltar");
        jLabel38.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel38MouseClicked(evt);
            }
        });

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel39.setText("Gerir Funcionários");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/fred.png"))); // NOI18N
        rSPanelShadow1.add(jLabel1, java.awt.BorderLayout.CENTER);

        rSPanelShadow2.setMaximumSize(new java.awt.Dimension(275, 113));
        rSPanelShadow2.setMinimumSize(new java.awt.Dimension(275, 113));

        jLabel10.setText("Nome: ");

        jLabel11.setText("Fred Jossias");

        jLabel12.setText("Código:");

        jLabel13.setText("0123456");

        jLabel14.setText("Data Nasc. :");

        jLabel15.setText("01/02/1983");

        jLabel16.setText("BI:");

        jLabel17.setText("14568654685B");

        jLabel18.setText("Função: ");

        jLabel19.setText("Motorista");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout rSPanelShadow2Layout = new javax.swing.GroupLayout(rSPanelShadow2);
        rSPanelShadow2.setLayout(rSPanelShadow2Layout);
        rSPanelShadow2Layout.setHorizontalGroup(
            rSPanelShadow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelShadow2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rSPanelShadow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(rSPanelShadow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rSPanelShadow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
                .addContainerGap())
        );
        rSPanelShadow2Layout.setVerticalGroup(
            rSPanelShadow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelShadow2Layout.createSequentialGroup()
                .addGroup(rSPanelShadow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rSPanelShadow2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSPanelShadow2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rSPanelShadow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12))
                .addGap(6, 6, 6)
                .addGroup(rSPanelShadow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14))
                .addGap(6, 6, 6)
                .addGroup(rSPanelShadow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18))
                .addGroup(rSPanelShadow2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rSPanelShadow2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel16)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSPanelShadow2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel17))))
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Viagem e documentação");

        rSPanelShadow3.setMaximumSize(new java.awt.Dimension(330, 136));

        jLabel20.setText("Disponibilidade: ");

        jLabel21.setText("Ocupado");

        jLabel22.setText("Viagem:");

        jLabel23.setText("A1234");

        jLabel24.setText("Destino");

        jLabel25.setText("Inhambane - Vilanculos");

        jLabel32.setText("Expira Em:");

        jLabel40.setText("Carta de Condução :");

        jLabel42.setText("1564846488165");

        jLabel43.setText("20/08/2019");

        jLabel33.setText("Data Chegada :");

        jLabel41.setText("17/10/2018");

        jLabel44.setText("Profissional");

        jLabel45.setText("Categoria:");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout rSPanelShadow3Layout = new javax.swing.GroupLayout(rSPanelShadow3);
        rSPanelShadow3.setLayout(rSPanelShadow3Layout);
        rSPanelShadow3Layout.setHorizontalGroup(
            rSPanelShadow3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelShadow3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rSPanelShadow3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rSPanelShadow3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        rSPanelShadow3Layout.setVerticalGroup(
            rSPanelShadow3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSPanelShadow3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rSPanelShadow3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rSPanelShadow3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rSPanelShadow3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rSPanelShadow3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(jLabel41))
                .addGroup(rSPanelShadow3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rSPanelShadow3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel40)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(rSPanelShadow3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel42)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(rSPanelShadow3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel45)
                    .addComponent(jLabel44))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rSPanelShadow3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32)
                    .addComponent(jLabel43, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addComponent(jSeparator1)
        );

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Jorge Matavel", "Motorista", "Disponível"},
                {"Martinho", "Motorista", "Ocupado"},
                {"Celso Domingos", "Estivador", "Disponível"},
                {"Fred Jossias", "Motorista", "Ocupado"}
            },
            new String [] {
                "Nome", "Função", "Disponibilidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setRowHeight(22);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(40);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(50);
        }

        rSPanelShadow4.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/icons8_Phone_20px.png"))); // NOI18N
        jLabel46.setText("821234567");

        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/icons8_Envelope_20px.png"))); // NOI18N
        jLabel47.setText("propriofredjos@jossias.co.mz");

        jLabel48.setForeground(new java.awt.Color(0, 153, 0));
        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/icons8_Exercise_20px.png"))); // NOI18N
        jLabel48.setText("Activo");

        javax.swing.GroupLayout kPanelVerFuncLayout = new javax.swing.GroupLayout(kPanelVerFunc);
        kPanelVerFunc.setLayout(kPanelVerFuncLayout);
        kPanelVerFuncLayout.setHorizontalGroup(
            kPanelVerFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kPanelVerFuncLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kPanelVerFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kPanelVerFuncLayout.createSequentialGroup()
                        .addComponent(jLabel38)
                        .addGap(176, 176, 176)
                        .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kPanelVerFuncLayout.createSequentialGroup()
                        .addComponent(rSPanelShadow4, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(kPanelVerFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(kPanelVerFuncLayout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(jLabel9))
                            .addGroup(kPanelVerFuncLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rSPanelShadow2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(kPanelVerFuncLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(kPanelVerFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rSPanelShadow3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(kPanelVerFuncLayout.createSequentialGroup()
                                        .addComponent(rSPanelShadow1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(kPanelVerFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kPanelVerFuncLayout.setVerticalGroup(
            kPanelVerFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kPanelVerFuncLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kPanelVerFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel38)
                    .addComponent(jLabel39))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(kPanelVerFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rSPanelShadow4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(kPanelVerFuncLayout.createSequentialGroup()
                        .addGroup(kPanelVerFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kPanelVerFuncLayout.createSequentialGroup()
                                .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(rSPanelShadow1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rSPanelShadow2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(rSPanelShadow3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        kPanelGFRoot.add(kPanelVerFunc, "card2");

        kPanelRoot.add(kPanelGFRoot, "card2");

        kPanelRelatorios.setkBorderRadius(0);
        kPanelRelatorios.setkEndColor(new java.awt.Color(204, 255, 255));
        kPanelRelatorios.setkStartColor(new java.awt.Color(255, 255, 255));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/icons8_Back_Arrow_30px_2.png"))); // NOI18N
        jLabel34.setText("Voltar");
        jLabel34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel34MouseClicked(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel35.setText("Relatórios");

        javax.swing.GroupLayout kPanelRelatoriosLayout = new javax.swing.GroupLayout(kPanelRelatorios);
        kPanelRelatorios.setLayout(kPanelRelatoriosLayout);
        kPanelRelatoriosLayout.setHorizontalGroup(
            kPanelRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kPanelRelatoriosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel34)
                .addGap(176, 176, 176)
                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kPanelRelatoriosLayout.setVerticalGroup(
            kPanelRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kPanelRelatoriosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kPanelRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34)
                    .addComponent(jLabel35))
                .addContainerGap(429, Short.MAX_VALUE))
        );

        kPanelRoot.add(kPanelRelatorios, "card2");

        getContentPane().add(kPanelRoot, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 620, 470));

        kPanelNorth.setkBorderRadius(0);
        kPanelNorth.setkEndColor(new java.awt.Color(255, 255, 204));
        kPanelNorth.setkStartColor(new java.awt.Color(204, 255, 255));

        lbUserNameHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/icons8_Male_User_30px.png"))); // NOI18N
        lbUserNameHome.setText("username aqui");
        lbUserNameHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbUserNameHomeMouseClicked(evt);
            }
        });

        btNotificacoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/icons8_Notification_30px.png"))); // NOI18N
        btNotificacoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btNotificacoesMouseClicked(evt);
            }
        });

        lbNotificacoes.setText("Viagem Nr. 1364 - Coca-cola - Maputo -> Gaza foi terminada");

        javax.swing.GroupLayout kPanelNorthLayout = new javax.swing.GroupLayout(kPanelNorth);
        kPanelNorth.setLayout(kPanelNorthLayout);
        kPanelNorthLayout.setHorizontalGroup(
            kPanelNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kPanelNorthLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btNotificacoes)
                .addGap(18, 18, 18)
                .addComponent(lbNotificacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
                .addComponent(lbUserNameHome, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        kPanelNorthLayout.setVerticalGroup(
            kPanelNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kPanelNorthLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kPanelNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(kPanelNorthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbNotificacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbUserNameHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btNotificacoes))
                .addContainerGap())
        );

        getContentPane().add(kPanelNorth, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 800, 50));

        kPanelTitleBar.setkBorderRadius(0);
        kPanelTitleBar.setkEndColor(new java.awt.Color(0, 204, 204));
        kPanelTitleBar.setkStartColor(new java.awt.Color(102, 255, 255));
        kPanelTitleBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                kPanelTitleBarMouseDragged(evt);
            }
        });
        kPanelTitleBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                kPanelTitleBarMousePressed(evt);
            }
        });

        btExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/icons8_Close_Window_20px.png"))); // NOI18N
        btExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btExitMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("TRANSMAN");

        javax.swing.GroupLayout kPanelTitleBarLayout = new javax.swing.GroupLayout(kPanelTitleBar);
        kPanelTitleBar.setLayout(kPanelTitleBarLayout);
        kPanelTitleBarLayout.setHorizontalGroup(
            kPanelTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kPanelTitleBarLayout.createSequentialGroup()
                .addContainerGap(379, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(334, 334, 334)
                .addComponent(btExit))
        );
        kPanelTitleBarLayout.setVerticalGroup(
            kPanelTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kPanelTitleBarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(kPanelTitleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(btExit)))
        );

        getContentPane().add(kPanelTitleBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kbtRViagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kbtRViagemActionPerformed
        // TODO add your handling code here:
        kPanelRoot.removeAll();
            kPanelRoot.add(kPanelRViagem);
            kPanelRoot.repaint();
            kPanelRoot.revalidate(); 
    }//GEN-LAST:event_kbtRViagemActionPerformed

    private void kbtRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kbtRelatoriosActionPerformed
        // TODO add your handling code here
        kPanelRoot.removeAll();
            kPanelRoot.add(kPanelRelatorios);
            kPanelRoot.repaint();
            kPanelRoot.revalidate(); 
        
    }//GEN-LAST:event_kbtRelatoriosActionPerformed

    private void kbtVViagensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kbtVViagensActionPerformed
        // TODO add your handling code here:
        kPanelRoot.removeAll();
            kPanelRoot.add(kPanelVViagens);
            kPanelRoot.repaint();
            kPanelRoot.revalidate(); 
    }//GEN-LAST:event_kbtVViagensActionPerformed

    private void kbtGViaturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kbtGViaturasActionPerformed
        // TODO add your handling code here:
        kPanelRoot.removeAll();
            kPanelRoot.add(kPanelGViaturas);
            kPanelRoot.repaint();
            kPanelRoot.revalidate(); 
    }//GEN-LAST:event_kbtGViaturasActionPerformed

    private void kbtGFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kbtGFuncionariosActionPerformed
        // TODO add your handling code here:
       kPanelRoot.removeAll();
            kPanelRoot.add(kPanelGFRoot);
            kPanelRoot.repaint();
            kPanelRoot.revalidate(); 
    }//GEN-LAST:event_kbtGFuncionariosActionPerformed

    private void btExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btExitMouseClicked
        // TODO add your handling code here:
        ExitDialog exit=new ExitDialog();
        exit.setLocationRelativeTo(null);
        exit.setVisible(true);
        //System.exit(0);
    }//GEN-LAST:event_btExitMouseClicked

    private void kPanelTitleBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kPanelTitleBarMousePressed
        // TODO add your handling code here:
        new Drag(kPanelTitleBar).onPress(evt);
    }//GEN-LAST:event_kPanelTitleBarMousePressed

    private void kPanelTitleBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kPanelTitleBarMouseDragged
        // TODO add your handling code here:
        new Drag(kPanelTitleBar).moveWindow(evt);
    }//GEN-LAST:event_kPanelTitleBarMouseDragged

    private void lbUserNameHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbUserNameHomeMouseClicked
        // TODO add your handling code here:
        JOptionPane.showInputDialog("Alterar a password? [Y/N]");
    }//GEN-LAST:event_lbUserNameHomeMouseClicked

    private void jLabel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseClicked
        // TODO add your handling code here:
        kPanelRoot.removeAll();
        kPanelRoot.add(kPanelHome);
        kPanelRoot.repaint();
        kPanelRoot.revalidate();
    }//GEN-LAST:event_jLabel26MouseClicked

    private void btNotificacoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btNotificacoesMouseClicked
        // TODO add your handling code here:
        if(lbNotificacoes.isVisible()==false)
        lbNotificacoes.setVisible(true);
        else lbNotificacoes.setVisible(false);
    }//GEN-LAST:event_btNotificacoesMouseClicked

    private void jLabel28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseClicked
        // TODO add your handling code here:
        kPanelRoot.removeAll();
        kPanelRoot.add(kPanelHome);
        kPanelRoot.repaint();
        kPanelRoot.revalidate();
    }//GEN-LAST:event_jLabel28MouseClicked

    private void jLabel30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseClicked
        // TODO add your handling code here:
        kPanelRoot.removeAll();
        kPanelRoot.add(kPanelHome);
        kPanelRoot.repaint();
        kPanelRoot.revalidate();
    }//GEN-LAST:event_jLabel30MouseClicked

    private void jLabel34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel34MouseClicked
        // TODO add your handling code here:
        kPanelRoot.removeAll();
        kPanelRoot.add(kPanelHome);
        kPanelRoot.repaint();
        kPanelRoot.revalidate();
    }//GEN-LAST:event_jLabel34MouseClicked

    private void jLabel36MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel36MouseClicked
        // TODO add your handling code here:
        kPanelRoot.removeAll();
        kPanelRoot.add(kPanelHome);
        kPanelRoot.repaint();
        kPanelRoot.revalidate();
    }//GEN-LAST:event_jLabel36MouseClicked

    private void btPaneVerFuncMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btPaneVerFuncMouseEntered
        // TODO add your handling code here:
        setColor(btPaneVerFunc);
    }//GEN-LAST:event_btPaneVerFuncMouseEntered

    private void btPaneVerFuncMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btPaneVerFuncMouseExited
        // TODO add your handling code here:
        resetColor(btPaneVerFunc);
    }//GEN-LAST:event_btPaneVerFuncMouseExited

    private void btPaneVerFuncMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btPaneVerFuncMousePressed
        // TODO add your handling code here:
        //new Home_Data().show();
        kPanelGFRoot.removeAll();
        kPanelGFRoot.add(kPanelVerFunc);
        kPanelGFRoot.repaint();
        kPanelGFRoot.revalidate();
    }//GEN-LAST:event_btPaneVerFuncMousePressed

    private void btPaneAddFuncMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btPaneAddFuncMouseEntered
        // TODO add your handling code here:
        setColor(btPaneAddFunc);
    }//GEN-LAST:event_btPaneAddFuncMouseEntered

    private void btPaneAddFuncMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btPaneAddFuncMouseExited
        // TODO add your handling code here:
        resetColor(btPaneAddFunc);
    }//GEN-LAST:event_btPaneAddFuncMouseExited

    private void btPaneAddFuncMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btPaneAddFuncMousePressed
        // TODO add your handling code here:
        //just a sample.
        //new Students().show();
    }//GEN-LAST:event_btPaneAddFuncMousePressed

    private void btPaneAlterFuncMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btPaneAlterFuncMouseEntered
        // TODO add your handling code here
        setColor(btPaneAlterFunc);
    }//GEN-LAST:event_btPaneAlterFuncMouseEntered

    private void btPaneAlterFuncMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btPaneAlterFuncMouseExited
        // TODO add your handling code here:
        resetColor(btPaneAlterFunc);
    }//GEN-LAST:event_btPaneAlterFuncMouseExited

    private void jLabel38MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel38MouseClicked
        // TODO add your handling code here:
        kPanelGFRoot.removeAll();
        kPanelGFRoot.add(kPanelGFuncionarios);
        kPanelGFRoot.repaint();
        kPanelGFRoot.revalidate();
    }//GEN-LAST:event_jLabel38MouseClicked

    
    public void setColor(JPanel panel)
 {
     panel.setBackground(new java.awt.Color(0,204,204));
 }
 
 public void resetColor(JPanel panel)
 {
     panel.setBackground(new java.awt.Color(102,255,255));
 }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home("Username aqui").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton btEditarViaturas;
    private javax.swing.JLabel btExit;
    private javax.swing.JLabel btNotificacoes;
    private javax.swing.JPanel btPaneAddFunc;
    private javax.swing.JPanel btPaneAlterFunc;
    private javax.swing.JPanel btPaneVerFunc;
    private javax.swing.JLabel btSettings;
    private keeptoo.KButton btVerViaturas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelMenu;
    private com.alee.managers.language.updaters.JProgressBarLU jProgressBarLU1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private keeptoo.KButton kButton2;
    private keeptoo.KGradientPanel kPanelEmCurso;
    private keeptoo.KGradientPanel kPanelGFRoot;
    private keeptoo.KGradientPanel kPanelGFuncionarios;
    private keeptoo.KGradientPanel kPanelGViaturas;
    private keeptoo.KGradientPanel kPanelGViaturas1;
    private keeptoo.KGradientPanel kPanelHome;
    private keeptoo.KGradientPanel kPanelNorth;
    private keeptoo.KGradientPanel kPanelPendentes;
    private keeptoo.KGradientPanel kPanelRViagem;
    private keeptoo.KGradientPanel kPanelRelatorios;
    private keeptoo.KGradientPanel kPanelRoot;
    private keeptoo.KGradientPanel kPanelTerminadas;
    private keeptoo.KGradientPanel kPanelTitleBar;
    private keeptoo.KGradientPanel kPanelVViagens;
    private keeptoo.KGradientPanel kPanelVerFunc;
    private keeptoo.KButton kbtGFuncionarios;
    private keeptoo.KButton kbtGViaturas;
    private keeptoo.KButton kbtRViagem;
    private keeptoo.KButton kbtRelatorios;
    private keeptoo.KButton kbtVViagens;
    private javax.swing.JLabel lbClienteHome;
    private javax.swing.JLabel lbClienteHome1;
    private javax.swing.JLabel lbClienteHome2;
    private javax.swing.JLabel lbClienteHome3;
    private javax.swing.JLabel lbClienteHome4;
    private javax.swing.JLabel lbDestinoHome;
    private javax.swing.JLabel lbDestinoHome2;
    private javax.swing.JLabel lbDestinoHome3;
    private javax.swing.JLabel lbDestinoHome4;
    private javax.swing.JLabel lbDestinohome1;
    private javax.swing.JLabel lbEmCurso;
    private javax.swing.JLabel lbEmCursoTop;
    private javax.swing.JLabel lbNotificacoes;
    private javax.swing.JLabel lbOrigemHome;
    private javax.swing.JLabel lbOrigemHome1;
    private javax.swing.JLabel lbOrigemHome2;
    private javax.swing.JLabel lbOrigemHome3;
    private javax.swing.JLabel lbOrigemHome4;
    private javax.swing.JLabel lbPendentes;
    private javax.swing.JLabel lbPendentesTop;
    private javax.swing.JLabel lbTerminadas;
    private javax.swing.JLabel lbTerminadasTop;
    private javax.swing.JLabel lbUltimasViagens;
    private javax.swing.JLabel lbUserNameHome;
    private com.alee.laf.progressbar.WebProgressBar progressHome1;
    private com.alee.laf.progressbar.WebProgressBar progressHome3;
    private rojeru_san.RSPanelShadow rSPanelShadow1;
    private rojeru_san.RSPanelShadow rSPanelShadow2;
    private rojeru_san.RSPanelShadow rSPanelShadow3;
    private rojeru_san.RSPanelShadow rSPanelShadow4;
    private javax.swing.JSeparator sepHome;
    private com.alee.laf.progressbar.WebProgressBar webProgressBar2;
    private com.alee.laf.progressbar.WebProgressBar webProgressBar5;
    private com.alee.laf.progressbar.WebProgressBarStyle webProgressBarStyle1;
    private com.alee.laf.progressbar.WebProgressBarUI webProgressBarUI1;
    private com.alee.extended.progress.WebStepProgress webStepProgress1;
    private com.alee.extended.progress.WebStepProgressStyle webStepProgressStyle1;
    // End of variables declaration//GEN-END:variables
}
