/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JOptionPane;
import keeptoo.Drag;

/**
 *
 * @author JoseM
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        lbNotificacoes.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBarLU1 = new com.alee.managers.language.updaters.JProgressBarLU();
        webProgressBarUI1 = new com.alee.laf.progressbar.WebProgressBarUI();
        webStepProgressStyle1 = new com.alee.extended.progress.WebStepProgressStyle();
        webProgressBarStyle1 = new com.alee.laf.progressbar.WebProgressBarStyle();
        webStepProgress1 = new com.alee.extended.progress.WebStepProgress();
        jPanel1 = new javax.swing.JPanel();
        kbtRViagem = new keeptoo.KButton();
        kbtRelatorios = new keeptoo.KButton();
        kbtVViagens = new keeptoo.KButton();
        kbtGViaturas = new keeptoo.KButton();
        kbtGFuncionarios = new keeptoo.KButton();
        jLabel25 = new javax.swing.JLabel();
        kPanelRoot = new keeptoo.KGradientPanel();
        kPanelHome = new keeptoo.KGradientPanel();
        kGradientPanel3 = new keeptoo.KGradientPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        kGradientPanel4 = new keeptoo.KGradientPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        kGradientPanel5 = new keeptoo.KGradientPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        webProgressBar1 = new com.alee.laf.progressbar.WebProgressBar();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        webProgressBar2 = new com.alee.laf.progressbar.WebProgressBar();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        webProgressBar3 = new com.alee.laf.progressbar.WebProgressBar();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        webProgressBar5 = new com.alee.laf.progressbar.WebProgressBar();
        kPanelRViagem = new keeptoo.KGradientPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        kPanelVViagens = new keeptoo.KGradientPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        kPanelGViaturas = new keeptoo.KGradientPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        kPanelGFuncionarios = new keeptoo.KGradientPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        kPanelRelatorios = new keeptoo.KGradientPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        btNotificacoes = new javax.swing.JLabel();
        lbNotificacoes = new javax.swing.JLabel();
        kGradientPanel8 = new keeptoo.KGradientPanel();
        btExit = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        kbtRViagem.setBackground(new java.awt.Color(236, 236, 236));
        kbtRViagem.setForeground(new java.awt.Color(0, 0, 0));
        kbtRViagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/icons8_Truck_30px.png"))); // NOI18N
        kbtRViagem.setText("  Registrar Viagem");
        kbtRViagem.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        kbtRViagem.setkAllowGradient(false);
        kbtRViagem.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        kbtRViagem.setkBorderRadius(0);
        kbtRViagem.setkEndColor(new java.awt.Color(0, 255, 255));
        kbtRViagem.setkForeGround(new java.awt.Color(0, 0, 0));
        kbtRViagem.setkHoverForeGround(new java.awt.Color(102, 102, 102));
        kbtRViagem.setkPressedColor(new java.awt.Color(255, 255, 255));
        kbtRViagem.setkSelectedColor(new java.awt.Color(101, 198, 187));
        kbtRViagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kbtRViagemActionPerformed(evt);
            }
        });

        kbtRelatorios.setBackground(new java.awt.Color(236, 236, 236));
        kbtRelatorios.setForeground(new java.awt.Color(0, 0, 0));
        kbtRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/icons8_Stop_Pie_Chart_Report_30px.png"))); // NOI18N
        kbtRelatorios.setText("Relatórios");
        kbtRelatorios.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        kbtRelatorios.setkAllowGradient(false);
        kbtRelatorios.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        kbtRelatorios.setkBorderRadius(0);
        kbtRelatorios.setkEndColor(new java.awt.Color(0, 255, 255));
        kbtRelatorios.setkForeGround(new java.awt.Color(0, 0, 0));
        kbtRelatorios.setkHoverForeGround(new java.awt.Color(102, 102, 102));
        kbtRelatorios.setkPressedColor(new java.awt.Color(255, 255, 255));
        kbtRelatorios.setkSelectedColor(new java.awt.Color(101, 198, 187));
        kbtRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kbtRelatoriosActionPerformed(evt);
            }
        });

        kbtVViagens.setBackground(new java.awt.Color(236, 236, 236));
        kbtVViagens.setForeground(new java.awt.Color(0, 0, 0));
        kbtVViagens.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/icons8_Traveler_30px_3.png"))); // NOI18N
        kbtVViagens.setText("Ver viagens");
        kbtVViagens.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        kbtVViagens.setkAllowGradient(false);
        kbtVViagens.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        kbtVViagens.setkBorderRadius(0);
        kbtVViagens.setkEndColor(new java.awt.Color(0, 255, 255));
        kbtVViagens.setkForeGround(new java.awt.Color(0, 0, 0));
        kbtVViagens.setkHoverForeGround(new java.awt.Color(102, 102, 102));
        kbtVViagens.setkPressedColor(new java.awt.Color(255, 255, 255));
        kbtVViagens.setkSelectedColor(new java.awt.Color(101, 198, 187));
        kbtVViagens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kbtVViagensActionPerformed(evt);
            }
        });

        kbtGViaturas.setBackground(new java.awt.Color(236, 236, 236));
        kbtGViaturas.setForeground(new java.awt.Color(0, 0, 0));
        kbtGViaturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/icons8_Car_Service_30px_1.png"))); // NOI18N
        kbtGViaturas.setText("Gerir Viaturas");
        kbtGViaturas.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        kbtGViaturas.setkAllowGradient(false);
        kbtGViaturas.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        kbtGViaturas.setkBorderRadius(0);
        kbtGViaturas.setkEndColor(new java.awt.Color(0, 255, 255));
        kbtGViaturas.setkForeGround(new java.awt.Color(0, 0, 0));
        kbtGViaturas.setkHoverForeGround(new java.awt.Color(102, 102, 102));
        kbtGViaturas.setkPressedColor(new java.awt.Color(255, 255, 255));
        kbtGViaturas.setkSelectedColor(new java.awt.Color(101, 198, 187));
        kbtGViaturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kbtGViaturasActionPerformed(evt);
            }
        });

        kbtGFuncionarios.setBackground(new java.awt.Color(236, 236, 236));
        kbtGFuncionarios.setForeground(new java.awt.Color(0, 0, 0));
        kbtGFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/icons8_People_30px.png"))); // NOI18N
        kbtGFuncionarios.setText("Gerir Funcionários");
        kbtGFuncionarios.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        kbtGFuncionarios.setkAllowGradient(false);
        kbtGFuncionarios.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        kbtGFuncionarios.setkBorderRadius(0);
        kbtGFuncionarios.setkEndColor(new java.awt.Color(0, 255, 255));
        kbtGFuncionarios.setkForeGround(new java.awt.Color(0, 0, 0));
        kbtGFuncionarios.setkHoverForeGround(new java.awt.Color(102, 102, 102));
        kbtGFuncionarios.setkPressedColor(new java.awt.Color(255, 255, 255));
        kbtGFuncionarios.setkSelectedColor(new java.awt.Color(101, 198, 187));
        kbtGFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kbtGFuncionariosActionPerformed(evt);
            }
        });

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/icons8_Services_30px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(kbtRelatorios, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(kbtGFuncionarios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(kbtGViaturas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(kbtRViagem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(kbtVViagens, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel25)))
                .addGap(5, 5, 5))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(kbtRViagem, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kbtVViagens, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(kbtGViaturas, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(kbtGFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(kbtRelatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 180, 470));

        kPanelRoot.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 0, new java.awt.Color(204, 204, 204)));
        kPanelRoot.setForeground(new java.awt.Color(204, 204, 204));
        kPanelRoot.setkBorderRadius(0);
        kPanelRoot.setkEndColor(new java.awt.Color(204, 255, 255));
        kPanelRoot.setkStartColor(new java.awt.Color(255, 255, 255));
        kPanelRoot.setLayout(new java.awt.CardLayout());

        kPanelHome.setkBorderRadius(0);
        kPanelHome.setkEndColor(new java.awt.Color(204, 255, 255));
        kPanelHome.setkStartColor(new java.awt.Color(255, 255, 255));

        kGradientPanel3.setkEndColor(new java.awt.Color(242, 38, 19));
        kGradientPanel3.setkStartColor(new java.awt.Color(242, 23, 153));

        jLabel3.setText("Viagens Pendentes");

        jLabel8.setFont(new java.awt.Font("Josefin Sans", 1, 36)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("0");

        javax.swing.GroupLayout kGradientPanel3Layout = new javax.swing.GroupLayout(kGradientPanel3);
        kGradientPanel3.setLayout(kGradientPanel3Layout);
        kGradientPanel3Layout.setHorizontalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel3Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(45, 45, 45))
        );
        kGradientPanel3Layout.setVerticalGroup(
            kGradientPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        kGradientPanel4.setkEndColor(new java.awt.Color(52, 152, 219));
        kGradientPanel4.setkStartColor(new java.awt.Color(129, 207, 224));

        jLabel4.setText("Viagens em curso");

        jLabel7.setFont(new java.awt.Font("Josefin Sans", 1, 36)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("0");

        javax.swing.GroupLayout kGradientPanel4Layout = new javax.swing.GroupLayout(kGradientPanel4);
        kGradientPanel4.setLayout(kGradientPanel4Layout);
        kGradientPanel4Layout.setHorizontalGroup(
            kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel4Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        kGradientPanel4Layout.setVerticalGroup(
            kGradientPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        kGradientPanel5.setkEndColor(new java.awt.Color(0, 0, 0));
        kGradientPanel5.setkStartColor(new java.awt.Color(0, 230, 64));

        jLabel5.setText("Viagens terminadas");

        jLabel6.setFont(new java.awt.Font("Josefin Sans", 1, 36)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("0");

        javax.swing.GroupLayout kGradientPanel5Layout = new javax.swing.GroupLayout(kGradientPanel5);
        kGradientPanel5.setLayout(kGradientPanel5Layout);
        kGradientPanel5Layout.setHorizontalGroup(
            kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel5Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(45, 45, 45))
        );
        kGradientPanel5Layout.setVerticalGroup(
            kGradientPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Últimas Viagens");

        webProgressBar1.setValue(80);
        webProgressBar1.setBgBottom(new java.awt.Color(204, 255, 255));
        webProgressBar1.setBgTop(new java.awt.Color(204, 204, 255));
        webProgressBar1.setProgressBottomColor(new java.awt.Color(51, 255, 255));
        webProgressBar1.setProgressTopColor(new java.awt.Color(51, 255, 0));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Cliente");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Origem");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Destino");

        jLabel13.setText("Pepsi co.");

        jLabel14.setText("Maputo - Cidade");

        jLabel15.setText("Zambezia - Quelimane");

        jLabel16.setText("Mozal");

        webProgressBar2.setValue(20);
        webProgressBar2.setBgBottom(new java.awt.Color(204, 255, 255));
        webProgressBar2.setBgTop(new java.awt.Color(204, 204, 255));
        webProgressBar2.setProgressBottomColor(new java.awt.Color(51, 255, 255));
        webProgressBar2.setProgressTopColor(new java.awt.Color(51, 255, 0));

        jLabel17.setText("Maputo - Província");

        jLabel18.setText("SA - Johanesburg");

        jLabel19.setText("Fematro");

        webProgressBar3.setValue(56);
        webProgressBar3.setBgBottom(new java.awt.Color(204, 255, 255));
        webProgressBar3.setBgTop(new java.awt.Color(204, 204, 255));
        webProgressBar3.setProgressBottomColor(new java.awt.Color(51, 255, 255));
        webProgressBar3.setProgressTopColor(new java.awt.Color(51, 255, 0));

        jLabel20.setText("Maputo - Junta");

        jLabel21.setText("Inhambane - Maxixe");

        jLabel22.setText("Nampula - Nacala");

        jLabel23.setText("Maningue Nice");

        jLabel24.setText("Sofala - Beira");

        webProgressBar5.setValue(90);
        webProgressBar5.setBgBottom(new java.awt.Color(204, 255, 255));
        webProgressBar5.setBgTop(new java.awt.Color(204, 204, 255));
        webProgressBar5.setProgressBottomColor(new java.awt.Color(51, 255, 255));
        webProgressBar5.setProgressTopColor(new java.awt.Color(51, 255, 0));

        javax.swing.GroupLayout kPanelHomeLayout = new javax.swing.GroupLayout(kPanelHome);
        kPanelHome.setLayout(kPanelHomeLayout);
        kPanelHomeLayout.setHorizontalGroup(
            kPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kPanelHomeLayout.createSequentialGroup()
                .addGroup(kPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kPanelHomeLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(kPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kPanelHomeLayout.createSequentialGroup()
                                .addComponent(kGradientPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(kGradientPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(kGradientPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(kPanelHomeLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(kPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kPanelHomeLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(125, 125, 125)
                                .addComponent(jLabel14)
                                .addGap(81, 81, 81)
                                .addComponent(jLabel15))
                            .addGroup(kPanelHomeLayout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(webProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(kPanelHomeLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(139, 139, 139)
                                .addComponent(jLabel17)
                                .addGap(74, 74, 74)
                                .addComponent(jLabel18))
                            .addComponent(webProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(kPanelHomeLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(125, 125, 125)
                                .addComponent(jLabel20)
                                .addGap(90, 90, 90)
                                .addComponent(jLabel21))
                            .addComponent(webProgressBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(kPanelHomeLayout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(86, 86, 86)
                                .addComponent(jLabel22)
                                .addGap(91, 91, 91)
                                .addComponent(jLabel24))
                            .addComponent(webProgressBar5, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kPanelHomeLayout.setVerticalGroup(
            kPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kPanelHomeLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(kPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kGradientPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kGradientPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kGradientPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(kPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(webProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(kPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(webProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(kPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(webProgressBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(kPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addGroup(kPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel24)
                        .addComponent(jLabel22)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(webProgressBar5, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        kPanelRoot.add(kPanelHome, "card2");

        kPanelRViagem.setkBorderRadius(0);
        kPanelRViagem.setkEndColor(new java.awt.Color(204, 255, 255));
        kPanelRViagem.setkStartColor(new java.awt.Color(255, 255, 255));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/icons8_Back_Arrow_30px_2.png"))); // NOI18N
        jLabel26.setText("Voltar");
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel26MouseClicked(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel27.setText("Registrar viagem");

        javax.swing.GroupLayout kPanelRViagemLayout = new javax.swing.GroupLayout(kPanelRViagem);
        kPanelRViagem.setLayout(kPanelRViagemLayout);
        kPanelRViagemLayout.setHorizontalGroup(
            kPanelRViagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kPanelRViagemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addGap(176, 176, 176)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kPanelRViagemLayout.setVerticalGroup(
            kPanelRViagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kPanelRViagemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kPanelRViagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27))
                .addContainerGap(239, Short.MAX_VALUE))
        );

        kPanelRoot.add(kPanelRViagem, "card2");

        kPanelVViagens.setkBorderRadius(0);
        kPanelVViagens.setkEndColor(new java.awt.Color(204, 255, 255));
        kPanelVViagens.setkStartColor(new java.awt.Color(255, 255, 255));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/icons8_Back_Arrow_30px_2.png"))); // NOI18N
        jLabel28.setText("Voltar");
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel28MouseClicked(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel29.setText("Ver Viagens");

        javax.swing.GroupLayout kPanelVViagensLayout = new javax.swing.GroupLayout(kPanelVViagens);
        kPanelVViagens.setLayout(kPanelVViagensLayout);
        kPanelVViagensLayout.setHorizontalGroup(
            kPanelVViagensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kPanelVViagensLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28)
                .addGap(176, 176, 176)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kPanelVViagensLayout.setVerticalGroup(
            kPanelVViagensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kPanelVViagensLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kPanelVViagensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29))
                .addContainerGap(239, Short.MAX_VALUE))
        );

        kPanelRoot.add(kPanelVViagens, "card2");

        kPanelGViaturas.setkBorderRadius(0);
        kPanelGViaturas.setkEndColor(new java.awt.Color(204, 255, 255));
        kPanelGViaturas.setkStartColor(new java.awt.Color(255, 255, 255));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/icons8_Back_Arrow_30px_2.png"))); // NOI18N
        jLabel30.setText("Voltar");
        jLabel30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel30MouseClicked(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel31.setText("Gerir viaturas");

        javax.swing.GroupLayout kPanelGViaturasLayout = new javax.swing.GroupLayout(kPanelGViaturas);
        kPanelGViaturas.setLayout(kPanelGViaturasLayout);
        kPanelGViaturasLayout.setHorizontalGroup(
            kPanelGViaturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kPanelGViaturasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel30)
                .addGap(176, 176, 176)
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kPanelGViaturasLayout.setVerticalGroup(
            kPanelGViaturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kPanelGViaturasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kPanelGViaturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31))
                .addContainerGap(239, Short.MAX_VALUE))
        );

        kPanelRoot.add(kPanelGViaturas, "card2");

        kPanelGFuncionarios.setkBorderRadius(0);
        kPanelGFuncionarios.setkEndColor(new java.awt.Color(204, 255, 255));
        kPanelGFuncionarios.setkStartColor(new java.awt.Color(255, 255, 255));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/icons8_Back_Arrow_30px_2.png"))); // NOI18N
        jLabel32.setText("Voltar");
        jLabel32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel32MouseClicked(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel33.setText("Gerir Funcionários");

        javax.swing.GroupLayout kPanelGFuncionariosLayout = new javax.swing.GroupLayout(kPanelGFuncionarios);
        kPanelGFuncionarios.setLayout(kPanelGFuncionariosLayout);
        kPanelGFuncionariosLayout.setHorizontalGroup(
            kPanelGFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kPanelGFuncionariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32)
                .addGap(176, 176, 176)
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kPanelGFuncionariosLayout.setVerticalGroup(
            kPanelGFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kPanelGFuncionariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kPanelGFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32)
                    .addComponent(jLabel33))
                .addContainerGap(239, Short.MAX_VALUE))
        );

        kPanelRoot.add(kPanelGFuncionarios, "card2");

        kPanelRelatorios.setkBorderRadius(0);
        kPanelRelatorios.setkEndColor(new java.awt.Color(204, 255, 255));
        kPanelRelatorios.setkStartColor(new java.awt.Color(255, 255, 255));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/icons8_Back_Arrow_30px_2.png"))); // NOI18N
        jLabel34.setText("Voltar");
        jLabel34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel34MouseClicked(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel35.setText("Relatórios");

        javax.swing.GroupLayout kPanelRelatoriosLayout = new javax.swing.GroupLayout(kPanelRelatorios);
        kPanelRelatorios.setLayout(kPanelRelatoriosLayout);
        kPanelRelatoriosLayout.setHorizontalGroup(
            kPanelRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kPanelRelatoriosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel34)
                .addGap(176, 176, 176)
                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kPanelRelatoriosLayout.setVerticalGroup(
            kPanelRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kPanelRelatoriosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kPanelRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34)
                    .addComponent(jLabel35))
                .addContainerGap(239, Short.MAX_VALUE))
        );

        kPanelRoot.add(kPanelRelatorios, "card2");

        getContentPane().add(kPanelRoot, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 620, 470));

        kGradientPanel2.setkBorderRadius(0);
        kGradientPanel2.setkEndColor(new java.awt.Color(255, 255, 204));
        kGradientPanel2.setkStartColor(new java.awt.Color(204, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/icons8_Male_User_30px.png"))); // NOI18N
        jLabel1.setText("username aqui");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        btNotificacoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/icons8_Notification_30px.png"))); // NOI18N
        btNotificacoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btNotificacoesMouseClicked(evt);
            }
        });

        lbNotificacoes.setText("Viagem Nr. 1364 - Coca-cola - Maputo -> Gaza foi terminada");

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btNotificacoes)
                .addGap(18, 18, 18)
                .addComponent(lbNotificacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbNotificacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btNotificacoes))
                .addContainerGap())
        );

        getContentPane().add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 800, 50));

        kGradientPanel8.setkBorderRadius(0);
        kGradientPanel8.setkEndColor(new java.awt.Color(0, 204, 204));
        kGradientPanel8.setkStartColor(new java.awt.Color(102, 255, 255));
        kGradientPanel8.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                kGradientPanel8MouseDragged(evt);
            }
        });
        kGradientPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                kGradientPanel8MousePressed(evt);
            }
        });

        btExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/icons/icons8_Close_Window_20px.png"))); // NOI18N
        btExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btExitMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("TRANSMAN");

        javax.swing.GroupLayout kGradientPanel8Layout = new javax.swing.GroupLayout(kGradientPanel8);
        kGradientPanel8.setLayout(kGradientPanel8Layout);
        kGradientPanel8Layout.setHorizontalGroup(
            kGradientPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel8Layout.createSequentialGroup()
                .addContainerGap(379, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(334, 334, 334)
                .addComponent(btExit))
        );
        kGradientPanel8Layout.setVerticalGroup(
            kGradientPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(kGradientPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(btExit)))
        );

        getContentPane().add(kGradientPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kbtRViagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kbtRViagemActionPerformed
        // TODO add your handling code here:
        kPanelRoot.removeAll();
            kPanelRoot.add(kPanelRViagem);
            kPanelRoot.repaint();
            kPanelRoot.revalidate(); 
    }//GEN-LAST:event_kbtRViagemActionPerformed

    private void kbtRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kbtRelatoriosActionPerformed
        // TODO add your handling code here
        kPanelRoot.removeAll();
            kPanelRoot.add(kPanelRelatorios);
            kPanelRoot.repaint();
            kPanelRoot.revalidate(); 
        
    }//GEN-LAST:event_kbtRelatoriosActionPerformed

    private void kbtVViagensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kbtVViagensActionPerformed
        // TODO add your handling code here:
        kPanelRoot.removeAll();
            kPanelRoot.add(kPanelVViagens);
            kPanelRoot.repaint();
            kPanelRoot.revalidate(); 
    }//GEN-LAST:event_kbtVViagensActionPerformed

    private void kbtGViaturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kbtGViaturasActionPerformed
        // TODO add your handling code here:
        kPanelRoot.removeAll();
            kPanelRoot.add(kPanelGViaturas);
            kPanelRoot.repaint();
            kPanelRoot.revalidate(); 
    }//GEN-LAST:event_kbtGViaturasActionPerformed

    private void kbtGFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kbtGFuncionariosActionPerformed
        // TODO add your handling code here:
       kPanelRoot.removeAll();
            kPanelRoot.add(kPanelGFuncionarios);
            kPanelRoot.repaint();
            kPanelRoot.revalidate(); 
    }//GEN-LAST:event_kbtGFuncionariosActionPerformed

    private void btExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btExitMouseClicked
        // TODO add your handling code here:
        
        System.exit(0);
    }//GEN-LAST:event_btExitMouseClicked

    private void kGradientPanel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel8MousePressed
        // TODO add your handling code here:
        new Drag(kGradientPanel8).onPress(evt);
    }//GEN-LAST:event_kGradientPanel8MousePressed

    private void kGradientPanel8MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel8MouseDragged
        // TODO add your handling code here:
        new Drag(kGradientPanel8).moveWindow(evt);
    }//GEN-LAST:event_kGradientPanel8MouseDragged

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        JOptionPane.showInputDialog("Alterar a password? [Y/N]");
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseClicked
        // TODO add your handling code here:
        kPanelRoot.removeAll();
        kPanelRoot.add(kPanelHome);
        kPanelRoot.repaint();
        kPanelRoot.revalidate();
    }//GEN-LAST:event_jLabel26MouseClicked

    private void btNotificacoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btNotificacoesMouseClicked
        // TODO add your handling code here:
        if(lbNotificacoes.isVisible()==false)
        lbNotificacoes.setVisible(true);
        else lbNotificacoes.setVisible(false);
    }//GEN-LAST:event_btNotificacoesMouseClicked

    private void jLabel28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseClicked
        // TODO add your handling code here:
        kPanelRoot.removeAll();
        kPanelRoot.add(kPanelHome);
        kPanelRoot.repaint();
        kPanelRoot.revalidate();
    }//GEN-LAST:event_jLabel28MouseClicked

    private void jLabel30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseClicked
        // TODO add your handling code here:
        kPanelRoot.removeAll();
        kPanelRoot.add(kPanelHome);
        kPanelRoot.repaint();
        kPanelRoot.revalidate();
    }//GEN-LAST:event_jLabel30MouseClicked

    private void jLabel32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseClicked
        // TODO add your handling code here:
        kPanelRoot.removeAll();
        kPanelRoot.add(kPanelHome);
        kPanelRoot.repaint();
        kPanelRoot.revalidate();
    }//GEN-LAST:event_jLabel32MouseClicked

    private void jLabel34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel34MouseClicked
        // TODO add your handling code here:
        kPanelRoot.removeAll();
        kPanelRoot.add(kPanelHome);
        kPanelRoot.repaint();
        kPanelRoot.revalidate();
    }//GEN-LAST:event_jLabel34MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btExit;
    private javax.swing.JLabel btNotificacoes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private com.alee.managers.language.updaters.JProgressBarLU jProgressBarLU1;
    private javax.swing.JSeparator jSeparator1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private keeptoo.KGradientPanel kGradientPanel3;
    private keeptoo.KGradientPanel kGradientPanel4;
    private keeptoo.KGradientPanel kGradientPanel5;
    private keeptoo.KGradientPanel kGradientPanel8;
    private keeptoo.KGradientPanel kPanelGFuncionarios;
    private keeptoo.KGradientPanel kPanelGViaturas;
    private keeptoo.KGradientPanel kPanelHome;
    private keeptoo.KGradientPanel kPanelRViagem;
    private keeptoo.KGradientPanel kPanelRelatorios;
    private keeptoo.KGradientPanel kPanelRoot;
    private keeptoo.KGradientPanel kPanelVViagens;
    private keeptoo.KButton kbtGFuncionarios;
    private keeptoo.KButton kbtGViaturas;
    private keeptoo.KButton kbtRViagem;
    private keeptoo.KButton kbtRelatorios;
    private keeptoo.KButton kbtVViagens;
    private javax.swing.JLabel lbNotificacoes;
    private com.alee.laf.progressbar.WebProgressBar webProgressBar1;
    private com.alee.laf.progressbar.WebProgressBar webProgressBar2;
    private com.alee.laf.progressbar.WebProgressBar webProgressBar3;
    private com.alee.laf.progressbar.WebProgressBar webProgressBar5;
    private com.alee.laf.progressbar.WebProgressBarStyle webProgressBarStyle1;
    private com.alee.laf.progressbar.WebProgressBarUI webProgressBarUI1;
    private com.alee.extended.progress.WebStepProgress webStepProgress1;
    private com.alee.extended.progress.WebStepProgressStyle webStepProgressStyle1;
    // End of variables declaration//GEN-END:variables
}
