package Model;
// Generated Oct 8, 2018 7:21:03 PM by Hibernate Tools 4.3.1



/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private ClienteId id;
     private String nome;

    public Cliente() {
    }

	
    public Cliente(ClienteId id) {
        this.id = id;
    }
    public Cliente(ClienteId id, String nome) {
       this.id = id;
       this.nome = nome;
    }
   
    public ClienteId getId() {
        return this.id;
    }
    
    public void setId(ClienteId id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }




}


