package Model;
// Generated Oct 8, 2018 7:21:03 PM by Hibernate Tools 4.3.1



/**
 * ClienteId generated by hbm2java
 */
public class ClienteId  implements java.io.Serializable {


     private int nuit;
     private int idCliente;

    public ClienteId() {
    }

    public ClienteId(int nuit, int idCliente) {
       this.nuit = nuit;
       this.idCliente = idCliente;
    }
   
    public int getNuit() {
        return this.nuit;
    }
    
    public void setNuit(int nuit) {
        this.nuit = nuit;
    }
    public int getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ClienteId) ) return false;
		 ClienteId castOther = ( ClienteId ) other; 
         
		 return (this.getNuit()==castOther.getNuit())
 && (this.getIdCliente()==castOther.getIdCliente());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getNuit();
         result = 37 * result + this.getIdCliente();
         return result;
   }   


}


