package Model;
// Generated Oct 6, 2018 5:25:52 PM by Hibernate Tools 4.3.1



/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private int nuit;
     private String nome;

    public Cliente() {
    }

	
    public Cliente(int nuit) {
        this.nuit = nuit;
    }
    public Cliente(int nuit, String nome) {
       this.nuit = nuit;
       this.nome = nome;
    }
   
    public int getNuit() {
        return this.nuit;
    }
    
    public void setNuit(int nuit) {
        this.nuit = nuit;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }




}


