package Model;
// Generated Oct 8, 2018 7:21:03 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Funcionario generated by hbm2java
 */
public class Funcionario  implements java.io.Serializable {


     private int idFuncionario;
     private String nome;
     private Date dataNascimento;
     private Date dataAdmissao;
     private String funcao;
     private String numBi;
     private String status;

    public Funcionario() {
    }

	
    public Funcionario(int idFuncionario) {
        this.idFuncionario = idFuncionario;
    }
    public Funcionario(int idFuncionario, String nome, Date dataNascimento, Date dataAdmissao, String funcao, String numBi, String status) {
       this.idFuncionario = idFuncionario;
       this.nome = nome;
       this.dataNascimento = dataNascimento;
       this.dataAdmissao = dataAdmissao;
       this.funcao = funcao;
       this.numBi = numBi;
       this.status = status;
    }
   
    public int getIdFuncionario() {
        return this.idFuncionario;
    }
    
    public void setIdFuncionario(int idFuncionario) {
        this.idFuncionario = idFuncionario;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Date getDataNascimento() {
        return this.dataNascimento;
    }
    
    public void setDataNascimento(Date dataNascimento) {
        this.dataNascimento = dataNascimento;
    }
    public Date getDataAdmissao() {
        return this.dataAdmissao;
    }
    
    public void setDataAdmissao(Date dataAdmissao) {
        this.dataAdmissao = dataAdmissao;
    }
    public String getFuncao() {
        return this.funcao;
    }
    
    public void setFuncao(String funcao) {
        this.funcao = funcao;
    }
    public String getNumBi() {
        return this.numBi;
    }
    
    public void setNumBi(String numBi) {
        this.numBi = numBi;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


