package Model;
// Generated Oct 8, 2018 7:21:03 PM by Hibernate Tools 4.3.1



/**
 * Veiculo generated by hbm2java
 */
public class Veiculo  implements java.io.Serializable {


     private VeiculoId id;
     private String marca;
     private String modelo;
     private Integer ano;
     private Double kilometragem;
     private String status;
     private String categoria;
     private String tipo;
     private Double peso;
     private Double volume;
     private Integer lotacao;

    public Veiculo() {
    }

	
    public Veiculo(VeiculoId id) {
        this.id = id;
    }
    public Veiculo(VeiculoId id, String marca, String modelo, Integer ano, Double kilometragem, String status, String categoria, String tipo, Double peso, Double volume, Integer lotacao) {
       this.id = id;
       this.marca = marca;
       this.modelo = modelo;
       this.ano = ano;
       this.kilometragem = kilometragem;
       this.status = status;
       this.categoria = categoria;
       this.tipo = tipo;
       this.peso = peso;
       this.volume = volume;
       this.lotacao = lotacao;
    }
   
    public VeiculoId getId() {
        return this.id;
    }
    
    public void setId(VeiculoId id) {
        this.id = id;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public Integer getAno() {
        return this.ano;
    }
    
    public void setAno(Integer ano) {
        this.ano = ano;
    }
    public Double getKilometragem() {
        return this.kilometragem;
    }
    
    public void setKilometragem(Double kilometragem) {
        this.kilometragem = kilometragem;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Double getPeso() {
        return this.peso;
    }
    
    public void setPeso(Double peso) {
        this.peso = peso;
    }
    public Double getVolume() {
        return this.volume;
    }
    
    public void setVolume(Double volume) {
        this.volume = volume;
    }
    public Integer getLotacao() {
        return this.lotacao;
    }
    
    public void setLotacao(Integer lotacao) {
        this.lotacao = lotacao;
    }




}


