package Model;
// Generated Oct 8, 2018 7:21:03 PM by Hibernate Tools 4.3.1



/**
 * VeiculoId generated by hbm2java
 */
public class VeiculoId  implements java.io.Serializable {


     private String matricula;
     private int idVeiculo;

    public VeiculoId() {
    }

    public VeiculoId(String matricula, int idVeiculo) {
       this.matricula = matricula;
       this.idVeiculo = idVeiculo;
    }
   
    public String getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(String matricula) {
        this.matricula = matricula;
    }
    public int getIdVeiculo() {
        return this.idVeiculo;
    }
    
    public void setIdVeiculo(int idVeiculo) {
        this.idVeiculo = idVeiculo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VeiculoId) ) return false;
		 VeiculoId castOther = ( VeiculoId ) other; 
         
		 return ( (this.getMatricula()==castOther.getMatricula()) || ( this.getMatricula()!=null && castOther.getMatricula()!=null && this.getMatricula().equals(castOther.getMatricula()) ) )
 && (this.getIdVeiculo()==castOther.getIdVeiculo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getMatricula() == null ? 0 : this.getMatricula().hashCode() );
         result = 37 * result + this.getIdVeiculo();
         return result;
   }   


}


