package Model;
// Generated Oct 8, 2018 7:21:03 PM by Hibernate Tools 4.3.1



/**
 * Viagem generated by hbm2java
 */
public class Viagem  implements java.io.Serializable {


     private Integer idViagem;
     private String localPartida;
     private String provinciaPartida;
     private String localDestino;
     private String provinciaDestino;
     private String dataRegisto;
     private String dataPartida;
     private String dataChegada;
     private Integer numMotoristas;
     private String estado;
     private Integer nuitCliente;
     private Double distancia;
     private String matriculaVeiculo;
     private Double consumoCombustivel;
     private Double tempoEstimado;
     private Double valorAlimentacao;
     private Double valorAlojamento;
     private Double precoTotal;
     private String user;
     private String cliente;

    public Viagem() {
    }

    public Viagem(String localPartida, String provinciaPartida, String localDestino, String provinciaDestino, String dataRegisto, String dataPartida, String dataChegada, Integer numMotoristas, String estado, Integer nuitCliente, Double distancia, String matriculaVeiculo, Double consumoCombustivel, Double tempoEstimado, Double valorAlimentacao, Double valorAlojamento, Double precoTotal, String user, String cliente) {
       this.localPartida = localPartida;
       this.provinciaPartida = provinciaPartida;
       this.localDestino = localDestino;
       this.provinciaDestino = provinciaDestino;
       this.dataRegisto = dataRegisto;
       this.dataPartida = dataPartida;
       this.dataChegada = dataChegada;
       this.numMotoristas = numMotoristas;
       this.estado = estado;
       this.nuitCliente = nuitCliente;
       this.distancia = distancia;
       this.matriculaVeiculo = matriculaVeiculo;
       this.consumoCombustivel = consumoCombustivel;
       this.tempoEstimado = tempoEstimado;
       this.valorAlimentacao = valorAlimentacao;
       this.valorAlojamento = valorAlojamento;
       this.precoTotal = precoTotal;
       this.user = user;
       this.cliente = cliente;
    }
   
    public Integer getIdViagem() {
        return this.idViagem;
    }
    
    public void setIdViagem(Integer idViagem) {
        this.idViagem = idViagem;
    }
    public String getLocalPartida() {
        return this.localPartida;
    }
    
    public void setLocalPartida(String localPartida) {
        this.localPartida = localPartida;
    }
    public String getProvinciaPartida() {
        return this.provinciaPartida;
    }
    
    public void setProvinciaPartida(String provinciaPartida) {
        this.provinciaPartida = provinciaPartida;
    }
    public String getLocalDestino() {
        return this.localDestino;
    }
    
    public void setLocalDestino(String localDestino) {
        this.localDestino = localDestino;
    }
    public String getProvinciaDestino() {
        return this.provinciaDestino;
    }
    
    public void setProvinciaDestino(String provinciaDestino) {
        this.provinciaDestino = provinciaDestino;
    }
    public String getDataRegisto() {
        return this.dataRegisto;
    }
    
    public void setDataRegisto(String dataRegisto) {
        this.dataRegisto = dataRegisto;
    }
    public String getDataPartida() {
        return this.dataPartida;
    }
    
    public void setDataPartida(String dataPartida) {
        this.dataPartida = dataPartida;
    }
    public String getDataChegada() {
        return this.dataChegada;
    }
    
    public void setDataChegada(String dataChegada) {
        this.dataChegada = dataChegada;
    }
    public Integer getNumMotoristas() {
        return this.numMotoristas;
    }
    
    public void setNumMotoristas(Integer numMotoristas) {
        this.numMotoristas = numMotoristas;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Integer getNuitCliente() {
        return this.nuitCliente;
    }
    
    public void setNuitCliente(Integer nuitCliente) {
        this.nuitCliente = nuitCliente;
    }
    public Double getDistancia() {
        return this.distancia;
    }
    
    public void setDistancia(Double distancia) {
        this.distancia = distancia;
    }
    public String getMatriculaVeiculo() {
        return this.matriculaVeiculo;
    }
    
    public void setMatriculaVeiculo(String matriculaVeiculo) {
        this.matriculaVeiculo = matriculaVeiculo;
    }
    public Double getConsumoCombustivel() {
        return this.consumoCombustivel;
    }
    
    public void setConsumoCombustivel(Double consumoCombustivel) {
        this.consumoCombustivel = consumoCombustivel;
    }
    public Double getTempoEstimado() {
        return this.tempoEstimado;
    }
    
    public void setTempoEstimado(Double tempoEstimado) {
        this.tempoEstimado = tempoEstimado;
    }
    public Double getValorAlimentacao() {
        return this.valorAlimentacao;
    }
    
    public void setValorAlimentacao(Double valorAlimentacao) {
        this.valorAlimentacao = valorAlimentacao;
    }
    public Double getValorAlojamento() {
        return this.valorAlojamento;
    }
    
    public void setValorAlojamento(Double valorAlojamento) {
        this.valorAlojamento = valorAlojamento;
    }
    public Double getPrecoTotal() {
        return this.precoTotal;
    }
    
    public void setPrecoTotal(Double precoTotal) {
        this.precoTotal = precoTotal;
    }
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    public String getCliente() {
        return this.cliente;
    }
    
    public void setCliente(String cliente) {
        this.cliente = cliente;
    }




}


